import {
  createContext,
  useContext,
  useEffect,
  useMemo,
  useState,
  type ReactNode,
} from "react";

export type Language = "de" | "en";
export type ThemeMode = "dark" | "light";

type TranslationDict = Record<string, string>;

const translations: Record<Language, TranslationDict> = {
  de: {
    app_title: "Teltonika Control",
    devices_online: "{online}/{total} online",
    devices_loading: "Lade Geräte",
    flespi: "Flespi",
    sipgate: "Sipgate",
    connect: "Verbinden",
    disconnect: "Trennen",
    refresh: "Aktualisieren",
    language: "Sprache",
    theme: "Theme",
    dark: "Dunkel",
    light: "Hell",
    devices: "Geräte",
    no_devices: "Keine Geräte in Flespi. Lege welche in der Flespi-Console an.",
    no_selection: "Wähle ein Gerät aus.",
    online: "online",
    offline: "offline",
    last_seen: "Zuletzt {value}",
    no_contact: "Kein letzter Kontakt",
    type: "Typ",
    imei: "IMEI",
    save: "Speichern",
    saved: "Gespeichert",
    sending: "Sende…",
    send: "Senden",
    send_menu: "Sendeweg wählen",
    queued: "In Warteschlange",
    sent: "Gesendet",
    command_history: "Kommando-History",
    queue_link: "Queue",
    queue_modal_title: "Offene Queue",
    queue_modal_hint: "Offene GPRS-Kommandos. Sie verschwinden automatisch, sobald Flespi ein Result meldet.",
    queue_empty: "Keine offenen Kommandos.",
    queue_endpoint_missing: "Queue-API nicht erreichbar. Bitte Backend neu starten.",
    load: "Lade…",
    no_commands: "Noch keine Kommandos an dieses Gerät geschickt.",
    executed: "Ausgeführt",
    queue_id: "Queue-ID",
    flespi_response: "Flespi-Antwort",
    last_movement_change: "Letzte Bewegungsänderung",
    auto_stats: "Auto-Statistiken",
    status: "Status",
    battery: "Batterie",
    gsm: "GSM",
    satellites: "Satelliten",
    last_signal: "Letztes Signal",
    movement: "Bewegung",
    mileage: "Laufleistung",
    speed: "Geschwindigkeit",
    power: "Bordnetz",
    ignition: "Zündung",
    gps_age: "GPS Alter",
    yes: "ja",
    no: "nein",
    on: "an",
    off: "aus",
    map_osm: "OpenStreetMap",
    map_google: "Google Maps",
    latest_responses: "Letzte Flespi-Antworten",
    stats_position: "Position",
    obd_ready: "OBD bereit?",
    obd_signals_detected: "{count} Signale erkannt",
    obd_no_data: "Noch keine OBD-Daten",
    obd_no_data_long: "Noch keine OBD-/Fahrzeugwerte in der Telemetrie sichtbar.",
    obd_step_1: "1. Im Tab BT-OBD2 MAC und PIN des Adapters setzen.",
    obd_step_2: "2. Danach idealerweise cpureset mitsenden und 1-2 Minuten warten.",
    obd_step_3: "3. Fahrzeugzündung einschalten; viele Adapter liefern erst dann Daten.",
    obd_step_4:
      "4. Sobald Werte wie obd.*, vehicle.* oder can.* auftauchen, ist die OBD-Strecke aktiv.",
    sms_disabled: "SMS (Sipgate) — aus",
    gprs_flespi: "GPRS (Flespi)",
    sms_sipgate: "SMS (Sipgate)",
    save_number: "Speichern",
    saved_number: "Gespeichert: {value}",
    tab_status: "Status",
    tab_bt_obd2: "BT-OBD2",
    tab_apn: "APN",
    tab_server: "Server",
    tab_settings_read: "Lesen",
    tab_outputs: "Outputs",
    tab_raw: "Raw",
    status_query: "Status abfragen",
    status_hint: "Antwort kommt per Flespi zurück und erscheint im Panel „Letzte Flespi-Antworten“.",
    apn_set: "APN setzen",
    apn_hint: "Schreibt APN, Benutzer, Passwort und optional die APN-Authentifizierung.",
    apn_user: "APN Benutzer",
    apn_password: "APN Passwort",
    apn_auth: "APN Auth",
    server_setup: "Server Setup",
    server_setup_hint: "Setzt Server-Domain, Port und Protokoll. Optional wird auch der GPRS-Kontext aktiviert und ein CPU-Reset gesendet.",
    settings_read: "Aktuelle Settings holen",
    settings_read_hint: "Liest aktuelle APN-, Server- oder kombinierte Netzwerkeinstellungen per getparam aus. Antworten erscheinen im Bereich Letzte Flespi-Antworten.",
    settings_read_apn: "APN lesen",
    settings_read_server: "Server lesen",
    settings_read_network: "Netzwerk lesen",
    server_domain: "Server Domain",
    server_port: "Server Port",
    server_protocol: "Protokoll",
    gprs_context: "GPRS Kontext",
    bt_obd2_title: "BT-OBD2 Auto-Pair",
    bt_obd2_hint: "Setzt 800=1 (BT an), 807=2 (OBDII auto-connect), 804=MAC, 806=PIN.",
    bt_obd2_prep:
      "Für die OBD-Vorbereitung: nach dem Pairing am besten mit Reset senden, Zündung einschalten und 1-2 Minuten auf vehicle.* oder obd.* warten.",
    outputs_title: "Outputs / Reset",
    raw_title: "Rohes Kommando",
    raw_hint: "Für freie Teltonika-Befehle wie getparam 2001 oder setparam 123:1.",
    command_preview: "Kommando-Vorschau",
    preview_error: "Vorschaufehler",
    previous: "Zurück",
    next: "Weiter",
    page: "Seite",
    settings: "Einstellungen",
    menu: "Menü",
    open_menu: "Menü öffnen",
    close_menu: "Menü schließen",
    api_settings: "API & Zugangsdaten",
    save_settings: "Einstellungen speichern",
    settings_saved: "Einstellungen gespeichert",
    flespi_token: "Flespi Token",
    sipgate_sms_id: "Sipgate SMS-ID",
    sipgate_client_id: "Sipgate Client ID",
    sipgate_client_secret: "Sipgate Client Secret",
    sipgate_redirect_uri: "Sipgate Redirect URI",
    sipgate_token_id: "Sipgate Token ID",
    sipgate_token: "Sipgate Token",
    teltonika_sms_login: "Teltonika SMS Login",
    teltonika_sms_password: "Teltonika SMS Passwort",
    movement_changed_title: "Letzte Bewegungsänderung",
    forms: "Kommandos",
    show: "show",
    hide: "hide",
    hint_flespi_token: "API-Token mit Zugriff auf Geräte, Telemetrie und Commands.",
    hint_sipgate_oauth: "Empfohlen für OAuth-Apps. Client in sipgate anlegen, Redirect URI exakt übernehmen.",
    hint_sipgate_pat: "Einfacher Fallback per Personal Access Token für SMS-Versand.",
    hint_teltonika_sms_auth: "Optional. Nur nötig, wenn am Tracker SMS-Login/Passwort gesetzt ist.",
    device_config_modal_title: "Gerät hat geantwortet — Einstellungen übernehmen?",
    device_config_modal_hint: "Diese Werte werden in die APN- und Server-Formulare eingetragen und lokal gespeichert.",
    device_config_apply: "Übernehmen & speichern",
    device_config_dismiss: "Verwerfen",
    device_config_matches: "Übereinstimmend mit letzter Ablesung",
    device_config_mismatch: "⚠ Abweichung von letzter Ablesung",
    direct_sms_label: "Direkt / App",
    direct_sms_copy: "Kopieren",
    direct_sms_copied: "✓ Kopiert",
    direct_sms_open: "SMS-App öffnen ↗",
    direct_sms_no_recipient: "Empfänger eingeben um SMS-App zu öffnen",
  },
  en: {
    app_title: "Teltonika Control",
    devices_online: "{online}/{total} online",
    devices_loading: "Loading devices",
    flespi: "Flespi",
    sipgate: "Sipgate",
    connect: "Connect",
    disconnect: "Disconnect",
    refresh: "Refresh",
    language: "Language",
    theme: "Theme",
    dark: "Dark",
    light: "Light",
    devices: "Devices",
    no_devices: "No devices in Flespi. Create them in the Flespi console.",
    no_selection: "Select a device.",
    online: "online",
    offline: "offline",
    last_seen: "Last seen {value}",
    no_contact: "No recent contact",
    type: "Type",
    imei: "IMEI",
    save: "Save",
    saved: "Saved",
    sending: "Sending…",
    send: "Send",
    send_menu: "Choose send channel",
    queued: "Queued",
    sent: "Sent",
    command_history: "Command History",
    queue_link: "Queue",
    queue_modal_title: "Open Queue",
    queue_modal_hint: "Open GPRS commands. They disappear automatically once Flespi reports a result.",
    queue_empty: "No open commands.",
    queue_endpoint_missing: "Queue API is not reachable. Please restart the backend.",
    load: "Loading…",
    no_commands: "No commands sent to this device yet.",
    executed: "Executed",
    queue_id: "Queue ID",
    flespi_response: "Flespi response",
    last_movement_change: "Last movement change",
    auto_stats: "Vehicle Stats",
    status: "Status",
    battery: "Battery",
    gsm: "GSM",
    satellites: "Satellites",
    last_signal: "Last signal",
    movement: "Movement",
    mileage: "Mileage",
    speed: "Speed",
    power: "Power",
    ignition: "Ignition",
    gps_age: "GPS age",
    yes: "yes",
    no: "no",
    on: "on",
    off: "off",
    map_osm: "OpenStreetMap",
    map_google: "Google Maps",
    latest_responses: "Latest Flespi responses",
    stats_position: "Position",
    obd_ready: "OBD ready?",
    obd_signals_detected: "{count} signals detected",
    obd_no_data: "No OBD data yet",
    obd_no_data_long: "No OBD/vehicle values visible in telemetry yet.",
    obd_step_1: "1. In the BT-OBD2 tab, set the adapter MAC and PIN.",
    obd_step_2: "2. Prefer sending cpureset as well, then wait 1-2 minutes.",
    obd_step_3: "3. Turn the ignition on; many adapters only start then.",
    obd_step_4:
      "4. As soon as values like obd.*, vehicle.* or can.* appear, the OBD path is active.",
    sms_disabled: "SMS (Sipgate) — off",
    gprs_flespi: "GPRS (Flespi)",
    sms_sipgate: "SMS (Sipgate)",
    save_number: "Save",
    saved_number: "Saved: {value}",
    tab_status: "Status",
    tab_bt_obd2: "BT-OBD2",
    tab_apn: "APN",
    tab_server: "Server",
    tab_settings_read: "Read",
    tab_outputs: "Outputs",
    tab_raw: "Raw",
    status_query: "Query status",
    status_hint: "The response comes back via Flespi and appears in the latest responses panel.",
    apn_set: "Set APN",
    apn_hint: "Writes APN, username, password and optional APN authentication.",
    apn_user: "APN user",
    apn_password: "APN password",
    apn_auth: "APN auth",
    server_setup: "Server setup",
    server_setup_hint: "Sets server domain, port and protocol. Optionally enables the GPRS context and sends a CPU reset.",
    settings_read: "Fetch current settings",
    settings_read_hint: "Reads current APN, server or combined network settings via getparam. Responses appear in the latest Flespi responses panel.",
    settings_read_apn: "Read APN",
    settings_read_server: "Read server",
    settings_read_network: "Read network",
    server_domain: "Server domain",
    server_port: "Server port",
    server_protocol: "Protocol",
    gprs_context: "GPRS context",
    bt_obd2_title: "BT-OBD2 Auto Pair",
    bt_obd2_hint: "Sets 800=1 (BT on), 807=2 (OBDII auto-connect), 804=MAC, 806=PIN.",
    bt_obd2_prep:
      "For OBD prep: send with reset if possible, switch ignition on and wait 1-2 minutes for vehicle.* or obd.* values.",
    outputs_title: "Outputs / Reset",
    raw_title: "Raw command",
    raw_hint: "For free-form Teltonika commands like getparam 2001 or setparam 123:1.",
    command_preview: "Command preview",
    preview_error: "Preview error",
    previous: "Previous",
    next: "Next",
    page: "Page",
    settings: "Settings",
    menu: "Menu",
    open_menu: "Open menu",
    close_menu: "Close menu",
    api_settings: "API & Credentials",
    save_settings: "Save settings",
    settings_saved: "Settings saved",
    flespi_token: "Flespi token",
    sipgate_sms_id: "Sipgate SMS ID",
    sipgate_client_id: "Sipgate Client ID",
    sipgate_client_secret: "Sipgate Client Secret",
    sipgate_redirect_uri: "Sipgate Redirect URI",
    sipgate_token_id: "Sipgate Token ID",
    sipgate_token: "Sipgate Token",
    teltonika_sms_login: "Teltonika SMS login",
    teltonika_sms_password: "Teltonika SMS password",
    movement_changed_title: "Last movement change",
    forms: "Commands",
    show: "show",
    hide: "hide",
    hint_flespi_token: "API token with access to devices, telemetry and commands.",
    hint_sipgate_oauth: "Recommended for OAuth apps. Create the client in sipgate and copy the redirect URI exactly.",
    hint_sipgate_pat: "Simple fallback using a personal access token for SMS sending.",
    hint_teltonika_sms_auth: "Optional. Only needed if SMS login/password is set on the tracker.",
    device_config_modal_title: "Device responded — apply settings?",
    device_config_modal_hint: "These values will be filled into the APN and server forms and stored locally.",
    device_config_apply: "Apply & save",
    device_config_dismiss: "Dismiss",
    device_config_matches: "Matches last read",
    device_config_mismatch: "⚠ Differs from last read",
    direct_sms_label: "Direct / App",
    direct_sms_copy: "Copy",
    direct_sms_copied: "✓ Copied",
    direct_sms_open: "Open SMS app ↗",
    direct_sms_no_recipient: "Enter recipient to open SMS app",
  },
};

type UiContextValue = {
  language: Language;
  setLanguage: (language: Language) => void;
  theme: ThemeMode;
  setTheme: (theme: ThemeMode) => void;
  t: (key: string, vars?: Record<string, string | number>) => string;
};

const UiContext = createContext<UiContextValue | null>(null);

export const UiProvider = ({ children }: { children: ReactNode }) => {
  const [language, setLanguage] = useState<Language>("de");
  const [theme, setTheme] = useState<ThemeMode>("dark");

  useEffect(() => {
    const savedLanguage = window.localStorage.getItem("ui-language");
    const savedTheme = window.localStorage.getItem("ui-theme");
    if (savedLanguage === "de" || savedLanguage === "en") setLanguage(savedLanguage);
    if (savedTheme === "dark" || savedTheme === "light") setTheme(savedTheme);
  }, []);

  useEffect(() => {
    window.localStorage.setItem("ui-language", language);
    document.documentElement.lang = language;
  }, [language]);

  useEffect(() => {
    window.localStorage.setItem("ui-theme", theme);
    document.documentElement.dataset.theme = theme;
  }, [theme]);

  const value = useMemo<UiContextValue>(() => {
    const t = (key: string, vars?: Record<string, string | number>) => {
      let text = translations[language][key] ?? key;
      if (vars) {
        for (const [name, value] of Object.entries(vars)) {
          text = text.replace(`{${name}}`, String(value));
        }
      }
      return text;
    };

    return { language, setLanguage, theme, setTheme, t };
  }, [language, theme]);

  return <UiContext.Provider value={value}>{children}</UiContext.Provider>;
};

export const useUi = (): UiContextValue => {
  const value = useContext(UiContext);
  if (!value) throw new Error("useUi must be used inside UiProvider");
  return value;
};
